# Dynamic Programming

Follow the link to dynamic programming concepts

https://www.youtube.com/watch?v=oBt53YbR9Kk

## Normal Fibonacci Approach

In [1]:
def fib(n):
    if(n<=2):
        return 1
    return fib(n-1)+fib(n-2)

In [5]:
print (fib(6))
print(fib(7))
fib(8)

8
13


21

In [6]:
#This will cause multiple regression calls. Over (2^50) calls and hence will take too much time for computation
fib(50)

KeyboardInterrupt: 

## Fibonacci Approach using Memoization

Momoization : Storing the already computed values and using them

In [3]:
#Improvised time complexity = O(n) and space = O(n)
def fibM(n,memo={}):
    if(n in memo):
        return memo[n]
    if(n<=2):
        return 1
    memo[n]=fibM(n-1,memo)+fibM(n-2,memo)
    return memo[n]

In [4]:
fibM(6)

8

In [5]:
fibM(50)

12586269025

## Tabulation Approach

In [103]:
def fibT(n):
    table=[0]*(n+1) #creating a n+1 sized array of zeros
    table[1]=1
    for i in range(2,n+1):
        table[i]=table[i-1]+table[i-2]    #Adding the current value into the next two values
    return table[n]

In [104]:
print(fibT(6))
print(fibT(7))
print(fibT(8))
print(fibT(50))

8
13
21
12586269025


# Grid Traveller Problem

Given a 2D grid, find out how many ways u can use to traverse to bottom right corner. You can only move down or right.

## Recursive Approach

Time Complexity: 

Suppose n and m are given coordinates.

Then time to traverse the full tree formed= 2<sup>n+m</sup>

So time complexity= O(2<sup>n+m</sup>)

Space complexity=O(n+m)

In [17]:
def gridTraveler(m,n):
    if(m==1 and n==1): #Base case
        return 1
    if(m==0 or n==0):  #If the grid is complete or say it is invalid
        return 0
    return gridTraveler(m-1,n)+gridTraveler(m,n-1)


In [19]:
print(gridTraveler(1,1))
print(gridTraveler(2,3))
print(gridTraveler(3,2))
print(gridTraveler(3,3))
print(gridTraveler(18,18)) #This one will take much more time as there are more than 2^(18+18) grid calls

1
3
3
6


KeyboardInterrupt: 

## Memoization Approach

Time Complexity

Nodes which are really being traversed = n*m

So time complexity= O(n*m)

Space Complexity=O(n+m)

In [22]:
def gridTravelerM(m,n,memo={}):
    key=str(m)+','+str(n)      #Using this to avoid key collision, we need to put a separator like ','
    if(key in memo):
        return memo[key]
    if(m==1 and n==1): #Base case
        return 1
    if(m==0 or n==0):  #If the grid is complete or say it is invalid
        return 0
    memo[key]=gridTravelerM(m-1,n,memo)+gridTravelerM(m,n-1,memo)
    return memo[key]

In [23]:
print(gridTravelerM(1,1))
print(gridTravelerM(2,3))
print(gridTravelerM(3,2))
print(gridTravelerM(3,3))
print(gridTravelerM(18,18)) #This one will take much more time as there are more than 2^(18+18) grid calls

1
3
3
6
2333606220


## Tabulation Approach

In [93]:
#Using numpy arrays for zeros
#m+1 rows and n+1 columns
import numpy as np
def gridTravelerT(m,n):
    table=np.zeros((m+1,n+1))
    table[1][1]=1     #Base Case
    
    for i in range(m+1):
        for j in range(n+1):
            current=table[i][j]
            if(i+1<=m):               #Checking inbound index error
                table[i+1][j]+=current
            if(j+1<=n):
                table[i][j+1]+=current
    return table[m][n]

In [94]:
print(gridTravelerT(3,2))
print(gridTravelerT(4,4))
print(gridTravelerT(18,18))

3.0
20.0
2333606220.0


# canSum Problem

Given a target value and array of integers such that elements are greater than zero. Find out whether the elements can sum upto the target value.

Note:- A element can be used twice.

canSum(7,[3,4,5,7])=True

canSum(7,[4,5,6])=False

## Recursive Approach

Time Complexity: 

m is the target sum

n is the array length

In worst case if a element is -1. Then we have to subtract it exactly m times from given target Sum.

In that case height of the tree = m

And n numbers are there in array. So it determines the branching factor of nodes.

So number of times we have to subtract that number= n<sup>m</sup>

Time Complexity:- O(n<sup>m</sup>)

Space Complexity:- O(m)

In [34]:
def canSum(targetSum,numArray):
    if(targetSum==0):          #If the targetSum reaches value zero then return True
        return True
    
    if(targetSum<0):           #If targetSum becomes negative then return False
        return False
    
    for num in numArray:
        remainder=targetSum-num
        if (canSum(remainder,numArray)==True):       #Check after each subtraction if the targetSum becoms zero
            return True
    
    return False                 #Still after every iteration if targetSum is not 0 then return False

In [35]:
print(canSum(7,[2,3]))
print(canSum(7,[5,3,4,7]))
print(canSum(7,[2,4]))
print(canSum(300,[7,14])) #This will take too much time to subtract each number from it. TargetSum is too large

True
True
False


KeyboardInterrupt: 

## Memoization Approach

Time Complexity: O(m*n)

Space: O(m)

In [32]:
def canSumM(targetSum,numArray,memo={}):
    #numArray is not changing so won't use it as key in memo
    
    if(targetSum in memo):
        return memo[targetSum]
    
    if(targetSum==0):          #If the targetSum reaches value zero then return True
        return True
    
    if(targetSum<0):           #If targetSum becomes negative then return False
        return False
    
    for num in numArray:
        remainder=targetSum-num
        if (canSumM(remainder,numArray,memo)==True):#Check after each subtraction if the targetSum becoms zero
            memo[targetSum]=True
            return True
    
    memo[targetSum]=False
    return False                 #Still after every iteration if targetSum is not 0 then return False

In [37]:
print(canSumM(7,[2,3]))
print(canSumM(7,[5,3,4,7]))
print(canSumM(7,[2,4]))
print(canSumM(300,[7,14]))

True
True
True
False


# howSum Problem

Given a targetSum and array of numbers. Return the array of numbers which add upto the target sum. 

Note:- <ul><li>If there is no combination possible return null.</li>
    <li>If there are multiple combinations possible then return any one.</li></ul>
    
## Recursive Approach

m is the target sum

n is the array length

In worst case if a element is -1. Then we have to subtract it exactly m times from given target Sum.

In that case height of the tree = m

And n numbers are there in array. So it determines the branching factor of nodes.

So number of times we have to subtract that number= n<sup>m</sup>

Time Complexity:- O(m*n<sup>m</sup>)   This time we will also store the result in array of size m(Number of times we have to subtract numbers if they are 1).

Space Complexity:- O(m)

In [38]:
def howSum(targetSum,numArray):
    if(targetSum==0):
        return []
    if(targetSum<0):
        return None
    for num in numArray:
        remainder=targetSum-num
        remainderResult=howSum(remainder,numArray)
        if(remainderResult is not None):
            return [*remainderResult,num]     #If the array is returned means that targetSum was zero. So return the whole array along with the number
            
    return None

In [39]:
print(howSum(7,[2,3]))
print(howSum(7,[5,3,4,7]))
print(howSum(7,[2,4]))
print(howSum(300,[7,14])) #This will take too much time to subtract each number from it. TargetSum is too large

[3, 2, 2]
[4, 3]
None


KeyboardInterrupt: 

## Memoziation Approach

Time Complexity: O(m*n*m)

Space Complexity: O(m*m)        The memo array can be of length m

In [40]:
def howSumM(targetSum,numArray,memo={}):
    if(targetSum in memo):
        return memo[targetSum]
    if(targetSum==0):
        return []
    if(targetSum<0):
        return None
    for num in numArray:
        remainder=targetSum-num
        remainderResult=howSumM(remainder,numArray,memo)
        if(remainderResult is not None):
            memo[targetSum]=[*remainderResult,num]     #If the array is returned means that targetSum was zero. So return the whole array along with the number
            return memo[targetSum]
    memo[targetSum]=None
    return None

In [44]:
print(howSumM(7,[2,3]))
print(howSumM(9,[5,3,4,7]))
print(howSumM(8,[2,4]))
print(howSumM(300,[7,14]))

[3, 2, 2]
[4, 5]
[4, 4]
None


# 0/1 Knapsack Problem

**Using Memoization**

Formula used:- table[i][w]=max(table[i-1][w],table[i-1,w-w[i]]+P[i])

In [142]:
import numpy as np
def knapSack(Profit,Weight,capacity,n):
    row=n
    col=capacity
    table=np.zeros((row+1,col+1))
    for i in range(row+1):
        for j in range(col+1):
            if(i==0 and j==0):
                table[i][j]=0
            elif Weight[i-1] <= j:
                table[i][j] = max(Profit[i-1] + table[i-1][j-Weight[i-1]],table[i-1][j])
            else:
                table[i][j] = table[i-1][j]
    print(table)
    return table[n][capacity]

In [143]:
knapSack([1,2,5,6],[2,3,4,5],8,4)

[[0. 0. 0. 0. 0. 6. 6. 6. 6.]
 [0. 0. 1. 1. 1. 6. 6. 7. 7.]
 [0. 0. 1. 2. 2. 6. 6. 7. 8.]
 [0. 0. 1. 2. 5. 6. 6. 7. 8.]
 [0. 0. 1. 2. 5. 6. 6. 7. 8.]]


8.0

In [150]:
def pattern(n):
    if(n<=0):
        return 0
    print('*',end=" ")
    pattern(n-1)